### Prueba de factorizar
POST http://localhost:5085/api/transform/factorize
Content-Type: application/json

{
  "S": ["a b c", "a b d", "b a"]
}

### Prueba de eliminar recursión
POST http://localhost:5085/api/transform/eliminate-left-recursion
Content-Type: application/json

{
  "E": ["E + T", "T"],
  "T": ["T * F", "F"]
}

### Proceso paso a paso
POST http://localhost:5085/api/transform/step-by-step
Content-Type: application/json

{
  "S": ["a b c", "a b d", "b a"]
}
